### ISSUE TITLE
`tape` is loaded even without the `testing: tape` option

### ISSUE THREAD

**Issue by jgierer12** [ehmicky/log-process-errors#26] opened 2019-05-16 16:33 UTC
**Describe the bug**

When using `log-process-errors`, the following error is being thrown:

```
ERROR in /my-project/node_modules/log-process-errors/build/src/options/runners.js
Module not found: Error: Can't resolve 'tape' in '/my-project/node_modules/log-process-errors/build/src/options'
 @ /my-project/node_modules/log-process-errors/build/src/options/runners.js 17:11-26
 @ /my-project/node_modules/log-process-errors/build/src/options/testing.js
 @ /my-project/node_modules/log-process-errors/build/src/options/main.js
 @ /my-project/node_modules/log-process-errors/build/src/main.js
 @ my-file.js
```

As a workaround, I installed `tape` as a dependency of my project which solved the issue.

My environment is a little bit special, as it is a Yarn workspaces project, but as far as I can see that is not relevant to the issue.

Also note that I am using the `netlify-lambda` CLI to compile `my-file.js`, which uses webpack under the hood (not sure how its config looks) and using ES6 import syntax to load `log-process-errors`.

**Steps to reproduce**

Not sure, as I don't know which component(s) of my rather exotic setup are causing the issue.

**Environment**

```
  System:
    OS: Linux 5.0 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.41 GB / 15.39 GB
    Container: Yes
    Shell: 3.0.2 - /usr/bin/fish
  Binaries:
    Node: 11.14.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
```

**Can you submit a pull request?**

Yes, but it may take a while. When I have more time, I will first try to put together a minimal reproduction demo and then see how the issue can be fixed.

**Comment by ehmicky** [comment] 2019-05-16 16:36
Hi @jgierer12, thanks for reporting this issue!

Are you using the `testing` option with `tape` as a value?

**Comment by jgierer12** [comment] 2019-05-16 16:37
No, I'm not using any custom config at all.

**Comment by ehmicky** [comment] 2019-05-16 16:38
Thanks. Are you using `register/tape`?

**Comment by jgierer12** [comment] 2019-05-16 16:41
Nope, nothing test-related at all actually. Only a sibling package in the same workspace but outside the scope of the relevant package is using Jest.

**Comment by ehmicky** [comment] 2019-05-16 16:45
Ok so some background: the `testing` option is making tests fail when a process error is raised.

Each test runner works differently. For `tape`, I create a failing test using `require('tape').test('..', t => t.error(error))`. `require('tape')` is dynamically required and supposed to only be performed when the `testing` option is set to `tape`.

If you have a minimal reproduction demo, I would love to fix this bug, because this might impact other users with the same setup. Thanks!

**Comment by ehmicky** [comment] 2019-05-21 08:34
@jgierer12 Did you manage to reproduce it in a more minimal setup? Thanks!

**Comment by jgierer12** [comment] 2019-05-21 11:24
No, sorry, I tried for a while but didn't manage to reproduce this in a setup which I would be able to publish :confused: 

It must have something to do with the other dependencies I'm using, since I haven't been able to reproduce just with workspaces + netlify-lambda. On the upside, that probably makes it obscure enough for few other people to run into.

**Comment by ehmicky** [comment] 2019-05-21 12:42
Does it work if you uninstall `tape`? If not, could you please edit `node_modules/log-process-errors/build/src/options/runners.js` and add a `console.trace()` just before `require('tape')`? Like this you might get a better stack trace of what is calling that function.

**Comment by ehmicky** [comment] 2019-06-06 10:20
@jgierer12 if you could check this, this would help me fix this problem potentially for some users. Thanks!

**Comment by ehmicky** [comment] 2019-06-19 09:33
Closing but @jgierer12 feel free to comment.

**Closed by ehmicky** 2019-06-19 09:33 UTC
Labels: bug
